// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Roulette.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250409005154_03")]
    partial class _03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BetValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RouletteNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Winner")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("Models.RouletteNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("RouletteNumber");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = 1
                        },
                        new
                        {
                            Id = 4,
                            Color = 2
                        },
                        new
                        {
                            Id = 5,
                            Color = 1
                        },
                        new
                        {
                            Id = 6,
                            Color = 2
                        },
                        new
                        {
                            Id = 7,
                            Color = 1
                        },
                        new
                        {
                            Id = 8,
                            Color = 2
                        },
                        new
                        {
                            Id = 9,
                            Color = 1
                        },
                        new
                        {
                            Id = 10,
                            Color = 2
                        },
                        new
                        {
                            Id = 11,
                            Color = 2
                        },
                        new
                        {
                            Id = 12,
                            Color = 1
                        },
                        new
                        {
                            Id = 13,
                            Color = 2
                        },
                        new
                        {
                            Id = 14,
                            Color = 1
                        },
                        new
                        {
                            Id = 15,
                            Color = 2
                        },
                        new
                        {
                            Id = 16,
                            Color = 1
                        },
                        new
                        {
                            Id = 17,
                            Color = 2
                        },
                        new
                        {
                            Id = 18,
                            Color = 1
                        },
                        new
                        {
                            Id = 19,
                            Color = 1
                        },
                        new
                        {
                            Id = 20,
                            Color = 2
                        },
                        new
                        {
                            Id = 21,
                            Color = 1
                        },
                        new
                        {
                            Id = 22,
                            Color = 2
                        },
                        new
                        {
                            Id = 23,
                            Color = 1
                        },
                        new
                        {
                            Id = 24,
                            Color = 2
                        },
                        new
                        {
                            Id = 25,
                            Color = 1
                        },
                        new
                        {
                            Id = 26,
                            Color = 2
                        },
                        new
                        {
                            Id = 27,
                            Color = 1
                        },
                        new
                        {
                            Id = 28,
                            Color = 2
                        },
                        new
                        {
                            Id = 29,
                            Color = 2
                        },
                        new
                        {
                            Id = 30,
                            Color = 1
                        },
                        new
                        {
                            Id = 31,
                            Color = 2
                        },
                        new
                        {
                            Id = 32,
                            Color = 1
                        },
                        new
                        {
                            Id = 33,
                            Color = 2
                        },
                        new
                        {
                            Id = 34,
                            Color = 1
                        },
                        new
                        {
                            Id = 35,
                            Color = 2
                        },
                        new
                        {
                            Id = 36,
                            Color = 1
                        },
                        new
                        {
                            Id = 37,
                            Color = 0
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Models.Result", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
